### PR TITLE
search_provider: Update to intern classes changes

### PR DESCRIPTION
**Pull request by rafaelmardojai**

### CODE REVIEW

**Comment by mufeedali** [comment]
Only issue I'm seeing is that Language change in the app doesn't apply to search provider unless you manually kill the search_provider process. So we should probably find a way to fix that... Any ideas?

**Comment by rafaelmardojai** [comment]
> Only issue I'm seeing is that Language change in the app doesn't apply to search provider unless you manually kill the search_provider process. So we should probably find a way to fix that... Any ideas?

Yes, noticed that too. 

Problem is that currently we don´t have any signal to know that the translator changed. In the app, the prefs window calls the main window to reload the translator when the user changes the combo row. Ideally the main window should listen a signal and do it by itself.

**Comment by rafaelmardojai** [comment]
I tried connecting to `Settings.get().get_child('translators')` `changed` signal, but it never notified about `active` changing.

Docs says: Note that settings only emits this signal if you have read key at least once while a signal handler was already connected for key. 

And make sense because every time we call `get_child('translators')` we're creating a new instance.

**Comment by rafaelmardojai** [comment]
> And make sense because every time we call get_child('translators') we're creating a new instance.

This gave an idea

**Comment by rafaelmardojai** [comment]
Ok, last commit should resolve it. I tested it in the app but didn't have time to test the SP.

I have to go out so might test it later.

**Comment by mufeedali** [comment]
Just tested. Doesn't look like it fixed the search provider :(

**Comment by rafaelmardojai** [comment]
Hmm, weird, it works for me.

**Comment by mufeedali** [comment]
1. I search in the global search for something. "define" for example. It translates from "Auto" to the last target language (Albanian in my test).
2. Results appear.
3. Open Dialect and translate something else to another target language (French in my test).
4. Now search in Global search.
5. Still translates in Albanian.

Also, how do we get rid of the background app indicator?

**Comment by rafaelmardojai** [comment]
Oh, so it doesn't update to the lasted saved recent lang. This can be fixed by connecting to the whole `self.translator.settings::changed` signal I guess, seems like I dropped that in the process. 

But remember that Dialect doesn't save recent langs until you close the app.

**Comment by mufeedali** [comment]
> But remember that Dialect doesn't save recent langs until you close the app.

Yeah, but closing the main window isn't enough. You have to kill the search_provider process for the change to apply

**Comment by rafaelmardojai** [comment]
> Yeah, but closing the main window isn't enough. You have to kill the search_provider process for the change to apply

Yup, I just meant that with the fix you still need to close the window 😅.

**Review by mufeedali — APPROVED** [review]

**Comment by mufeedali** [comment]
Works as intended!

**Pull request merged**
