### PR TITLE
Improved support for LibreTranslate, some GTK4 fixes and other improvements

### PR DESCRIPTION
**Pull request by fushinari**
- [x] Suggestions
	- [x] Edit UI
	- [x] Basic support (LibreTranslate)
	- [x] Improve notifications to support more states (for showing successful suggestions)
- [x] Fix Shortcuts window.

### CODE REVIEW

**Comment by fushinari** [comment]
Now moved to other future PRs:

- [ ] API keys support (LibreTranslate, requires some changes on the LibreTranslate side)
	- [x] https://github.com/LibreTranslate/LibreTranslate/pull/162
	- [x] https://github.com/LibreTranslate/LibreTranslate/pull/164
	- [ ] https://github.com/LibreTranslate/LibreTranslate/pull/165
	- [ ] Maybe more
- [ ] File translation support. (May not do this for now.)

**Comment by rafaelmardojai** [comment]
I'm not sure about the fact that if you cancel the suggestion the previous text isn't reestablished. Or that will be too much over complication?

**Comment by fushinari** [comment]
I think that would be the expected behavior, should be fixed now. Can you test?

**Review by rafaelmardojai — APPROVED** [review]
Looks good!

**Pull request merged**
