### PR TITLE
DialectLangSelector: Fix various issues

### PR DESCRIPTION
**Pull request by rafaelmardojai**
- Always focus search entry
- Close language selector when Escape is pressed in search entry
- Choose the first language result when search entry is activated

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
I have tried to go back to `GtkListBox` and also keep the use of list models at the same time.

**Comment by fushinari** [comment]
> Choose the first language result when search entry is activated

I have the following warning when I try this:

```
(dialect:2): Gtk-WARNING **: 22:51:06.681: GtkText - did not receive a focus-out event.
If you handle this event, you must return
GDK_EVENT_PROPAGATE so the default handler
gets the event as well
```

It does work though.

Additionally, would it be better or worse to bring focus onto the search bar whenever inputting text? Like we do for the main window I mean?

**Comment by rafaelmardojai** [comment]
> I have the following warning when I try this:

Yeah, tried returning `Gdk.EVENT_PROPAGATE` but nothing.

> Additionally, would it be better or worse to bring focus onto the search bar whenever inputting text? Like we do for the main window I mean?

Like using `self.search.set_key_capture_widget(self)`?

**Comment by fushinari** [comment]
> Yeah, tried returning `Gdk.EVENT_PROPAGATE` but nothing.

I see. I guess it's safe to ignore though?

> Like using `self.search.set_key_capture_widget(self)`?

Would that capture all events and prevent keyboard navigation? I don't really know how it behaves.

**Comment by rafaelmardojai** [comment]
> Would that capture all events and prevent keyboard navigation? I don't really know how it behaves.

Yes, that property is for implementing "search as you type". This actually works, it search as you type in the popover, but the focus style of the entry is inconsistent (replacing the `grab_focus` with this).

**Comment by fushinari** [comment]
> Yes, that property is for implementing "search as you type". This actually works, it search as you type in the popover, but the focus style of the entry is inconsistent (replacing the grab_focus with this).

Okay, then let's do that.

Is it possible to make it so that the user doesn't have to use Tab to go to the list? Right now, the Down arrow key does take focus away from the search entry but doesnt give it to the list. So if it's not possible, we at least don't want Down arrow key taking focus away.

**Review by fushinari — APPROVED** [review]

**Pull request merged**
