### PR TITLE
Add doap file

### PR DESCRIPTION
**Pull request by rafaelmardojai**
Add doap file to show the maintainers on https://apps.gnome.org/.

See: https://blogs.gnome.org/sophieh/2021/08/15/apps-for-gnome-on-its-mark/

@fushinari please add yourself :P

### CODE REVIEW

**Comment by fushinari** [comment]
I thought GitHub support was not yet present?

**Comment by rafaelmardojai** [comment]
> I thought GitHub support was not yet present?

Me too, but when it lands probably will work like that :P

**Comment by rafaelmardojai** [comment]
But I guess that at least it will show the names, without the GitHub profile part.

**Comment by fushinari** [comment]
Ah, that's true. What order should the names be in? Alphabetical? Is there any guideline on that?

**Comment by rafaelmardojai** [comment]
I don't think there's one, alphabetically should be fine.

**Comment by fushinari** [comment]
d5e1a87 probably doesn't belong here :P but I felt it was needed. @rafaelmardojai what do you think?

**Review by fushinari — APPROVED** [review]

**Comment by rafaelmardojai** [comment]
Looks good!

**Comment by fushinari** [comment]
No worries, I'll just merge it :)

**Pull request merged**
