### PR TITLE
style: bye borders

### PR DESCRIPTION
**Pull request by fushinari**
Experimenting with a borderless design

Screenshot from 2021-11-25 17-35-29
Screenshot from 2021-11-25 17-35-10
Screenshot from 2021-11-25 17-34-53
Screenshot from 2021-11-25 17-34-40

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
How looks when the text is cut by the scroll?

**Comment by fushinari** [comment]
> How looks when the text is cut by the scroll?

Not good.
Screenshot from 2021-11-27 19-31-50

There are two ways I'm thinking of fixing this:
- Fade out the text next to the bottom of the textview.
- Show a separator when scrolling is available.

**Comment by fushinari** [comment]
Known issues:
- [ ] Styling for when text is scrollable
- [ ] Styling for pronunciations

Other issues that are more obvious now:
- [ ] Pronunciation takes up unnecessarily large amount of space

**Comment by fushinari** [comment]
@rafaelmardojai what do you think we should do about pronunciations?

**Comment by rafaelmardojai** [comment]
> what do you think we should do about pronunciations?

Maybe kept it as is for now, but move it bellow mistakes with a top and bottom borders

**Comment by fushinari** [comment]
Kind of a screenshot gallery.

Regular view:
Screenshot from 2021-12-29 13-05-27

With a mistake and a pronunciation:
Screenshot from 2021-12-29 13-05-07

With a mistake and view being scrollable:
Screenshot from 2021-12-29 13-05-36

With a mistake, a pronunciation and view being scrollable:
Screenshot from 2021-12-29 13-05-13

Am I happy with it? No. This feels somehow worse than before in any non-default state.

Maybe use earlier styling for mistakes as well?

**Comment by rafaelmardojai** [comment]
Looks good to me, the problem starts when you have mistakes, pronunciations and scrollable view, the mistakes bubble looks weird when it's inside a bordered box.

**Comment by fushinari** [comment]
@rafaelmardojai Can you have a look at the current state? A good test case is translating `안녕하세` from Korean to English.

**Review by rafaelmardojai — APPROVED** [review]
Everything looks good!

**Pull request merged**
